### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by tstibbs** [awslabs/aws-cognito-apigw-angular-auth#14]
Following the instructions in the readme failed at the instruction to run `npm start`. This calls `ng serve`, which fails with this error:
```
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (aws-cognito-apigw-angular\node_modules\@angular\cli\tasks\serve.js:22:63)
    at check_port_1.checkPort.then.port (aws-cognito-apigw-angular\node_modules\@angular\cli\commands\serve.js:103:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

It's not clear if this is a bug in angular-cli or something with this project. I noticed that the package.json refers to angular-cli 1.0.0 but using that version causes other problems (can't use the `new` command for one thing).

(I am on windows if that's relevant)

**Comment by tstibbs** [comment]
Update: turns out I shouldn't been running it from within the bundle that I downloaded from github. You need to run the commands in a totally seperate directly, not a subdirectory.
